//定义home页动作常量：
//获取Swipe
export const FETCH_SWIPE_REQUEST='HOME/FETCH_SWIPE_REQUEST';
export const FETCH_SWIPE_SUCCESS='HOME/FETCH_SWIPE_SUCCESS';
    //获取category
export const FETCH_CATEGORY_REQUEST='HOME/FETCH_CATEGORY_REQUEST';
export const FETCH_CATEGORY_SUCCESS='HOME/FETCH_CATEGORY_SUCCESS';
    //获取headline
export const FETCH_HEADLINE_REQUEST='HOME/FETCH_HEADLINE_REQUEST';
export const FETCH_HEADLINE_SUCCESS='HOME/FETCH_HEADLINE_SUCCESS';
    //获取discount
export const FETCH_DISCOUNT_REQUEST= 'HOME/FETCH_DISCOUNT_REQUEST';
export const FETCH_DISCOUNT_SUCCESS='HOME/FETCH_DISCOUNT_SUCCESS';
    //获取list
export const FETCH_HOME_LIST_REQUEST='HOME/FETCH_LIST_REQUEST';
export const FETCH_HOME_LIST_SUCCESS='HOME/FETCH_LIST_SUCCESS';
//定义kind页动作常量：
export const FETCH_KIND_REQUEST='FETCH_KIND_REQUEST';
export const FETCH_KIND_SUCCESS='FETCH_KIND_SUCCESS';
export const CHANGE_LEFT_INDEX='CHANGE_LEFT_INDEX';
//定义search页动作常量：
export const FETCH_SEARCH_FAIL='FETCH_SEARCH_FAIL';
export const FETCH_SEARCH_SUCCESS='FETCH_SEARCH_SUCCESS';
export const FETCH_SEARCH_HOT_REQUEST='FETCH_SEARCH_HOT_REQUEST';
export const FETCH_SEARCH_HOT_SUCCESS='FETCH_SEARCH_HOT_SUCCESS';
export const FETCH_SEARCH_HISTORY_REQUEST='FETCH_SEARCH_HISTORY_REQUEST';
export const FETCH_SEARCH_HISTORY_SUCCESS='FETCH_SEARCH_HISTORY_SUCCESS';
export const FETCH_CLEAR_HISTORY_SUCCESS='FETCH_CLEAR_HISTORY_SUCCESS';
export const SEARCH_RECOVER='SEARCH_RECOVER';

//定义lists页动作常量：
export const FETCH_LIST_REQUEST='FETCH_LIST_REQUEST';
export const FETCH_LIST_SUCCESS='FETCH_LIST_SUCCESS';
export const FETCH_FILTERDATA_REQUEST='FETCH_FILTERDATA_REQUEST';
export const FETCH_FILTERDATA_SUCCESS='FETCH_FILTERDATA_SUCCESS';
export const CHANGE_BARTAB='CHANGE_BARTAB';
export const CHANGE_FILTER_TYPE='CHANGE_FILTER_TYPE';
export const RECOVER='RECOVER';
//定义detail页动作常量：
export const FETCH_DETAIL_REQUEST='FETCH_DETAIL_REQUEST';
export const FETCH_DETAIL_SUCCESS='FETCH_DETAIL_SUCCESS';
export const CHANGE_NUMBER='CHANGE_NUMBER';
export const ADD_CART='ADD_CART';
export const CANCEL_COLLECT='CANCEL_COLLECT';
//定义personal(reg,login)页动作常量：
export const FETCH_REG_SUCCESS='FETCH_REG_SUCCESS';
export const FETCH_REG_FAIL='FETCH_REG_FAIL';
export const CLEAR_APPEAR='CLEAR_APPEAR';
export const FETCH_LOGIN='FETCH_LOGIN';
export const FETCH_LOGIN_FAIL='FETCH_LOGIN_FAIL';
export const FETCH_LOGINOUT_SUCCESS='FETCH_LOGINOUT_SUCCESS';
export const CHANGE_TWOPASSWORDS_ERROR='CHANGE_TWOPASSWORDS_ERROR';
export const CHANGE_PASSWORD_SUCCESS='CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAIL='CHANGE_PASSWORD_FAIL';
export const FETCH_VALIDATE='FETCH_VALIDATE';
export const WRITE_OFF_SUCCESS='WRITE_OFF_SUCCESS';
export const INITIALIZER_NUM='INITIALIZER_NUM';
export const FIND_CART='FIND_CART';
export const CLEAR_GOODSNUM='CLEAR_GOODSNUM';
export const WRITE_OFF_CART='WRITE_OFF_CART';
export const ADD_COLLECT_SUCCESS='ADD_COLLECT_SUCCESS';
export const CHANGE_COLLECT_KEY='CHANGE_COLLECT_KEY';
export const FIND_COLLECT='FIND_COLLECT';
export const FETCH_COLLECT_SUCCESS='FETCH_COLLECT_SUCCESS';
export const FETCH_COLLECT_FAIL='FETCH_COLLECT_FAIL';
export const CHANGE_EDIT='CHANGE_EDIT';
export const ALL_CHANGE_EDIT='ALL_CHANGE_EDIT';
export const FETCH_CART='FETCH_CART';
export const CHANGE_CHECKED='CHANGE_CHECKED';
export const CHANGE_ALL_CHECKED='CHANGE_ALL_CHECKED';
export const UPDATE_USER_CART='UPDATE_USER_CART';
export const DELETE_CART_INFO='DELETE_CART_INFO';
export const EMPTY_ALL='EMPTY_ALL';
export const FETCH_VALIDATE_FAIL='FETCH_VALIDATE_FAIL';

export const CHANGE_BOTTOM_ACTIVE_TYPE='CHANGE_BOTTOM_ACTIVE_TYPE';

